name: Triggers
run-name: Praxis 3 Triggers!
on:
  push:  #PUSH
    branches: ['main', 'aprendiendo-**']
    paths: ['**.yml']
  
  pull_request:  # PR
    types: [opened, labeled]
    branches: ['main', 'aprendiendo-**']
    paths: ['**.yml']
    
  schedule:  # SCHEDULE
    - cron: '59 23 * * SUN'
  
  workflow_dispatch:  # WORKFLOW_DISPATCH

jobs:
  hola-mundo:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: echo
        run: echo "hello world"

      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV      

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node hola_mundo.js
